# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.define "u5" do |u1|
    u1.vm.box = "ubuntu/xenial64"
    u1.vm.network "private_network", ip: "192.168.34.2"
    u1.vm.network "public_network"
    u1.vm.synced_folder "./", "/root/server"
    u1.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y apache2 socat ipvsadm bridge-utils

      # install docker-ce
      apt-get remove docker docker-engine docker.io containerd runc
      apt-get install -y \
    linux-image-extra-$(uname -r) \
    linux-image-extra-virtual
      apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      apt-key fingerprint 0EBFCD88
      add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
     apt-get update
     apt-get install -y docker-ce

      # turnoff ufw
      ufw disable
    SHELL
  end

end
