[global.config]
  as = 65000
  router-id = "192.168.33.5"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "192.168.33.6"
    peer-as = 65000
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv4-unicast"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv6-unicast"
