#!/bin/bash

export VIP=192.168.161.123

inject() {
  key=$(< ${1})
  vagrant ssh ${2} -c "echo ${key} | sudo tee -a /root/.ssh/authorized_keys"
}

inject_keys_to_all() {
  export PRIVATE_KEY="$PWD/test-privkey"
  ssh-keygen -t rsa -b 4096 -C "hi" -N '' -f ${PRIVATE_KEY} 
  local private_key=${PRIVATE_KEY}
  for i in $(seq 8); do inject ${private_key}.pub u${i}; done
cat > $PWD/env.sh << EOF
  alias gotou1="ssh -t -i ${private_key} root@192.168.33.2 \"cd /root/server/scripts; bash\""
  alias gotou2="ssh -t -i ${private_key} root@192.168.33.3 \"cd /root/server/scripts; bash\""
  alias gotou3="ssh -t -i ${private_key} root@192.168.33.4 \"cd /root/server/scripts; bash\""
  alias gotou4="ssh -t -i ${private_key} root@192.168.33.5 \"cd /root/server/scripts; bash\""
  alias gotou5="ssh -t -i ${private_key} root@192.168.33.6 \"cd /root/server/scripts; bash\""
  alias gotou6="ssh -t -i ${private_key} root@192.168.34.2 \"cd /root/server/scripts; bash\""
  alias gotou7="ssh -t -i ${private_key} root@192.168.35.2 \"cd /root/server/scripts; bash\""
  alias gotou8="ssh -t -i ${private_key} root@192.168.36.2 \"cd /root/server/scripts; bash\""
EOF
}

change_local_route() {
	if ip r | grep ${VIP} >/dev/null 2>&1; then
		ip r del ${VIP}
	fi
	ip r add ${VIP}/32 via ${1}
}

enable_ip_forward_on_mac() {
	sudo sysctl -w net.inet.ip.forwarding=1
}
